config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "blogs#opening"

  resources :blogs do
    collection do
      get 'opening'
      get 'list'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def opening
  end

  def index
    @blogs = Blog.all.page(params[:page]).per(5).order('id DESC')
  end

  def new
    @blog = Blog.new
  end

  def create
    Blog.create(create_params)
    redirect_to '/blogs'
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def list
    @blogs = Blog.all.page(params[:page]).per(10).order('id ASC')
  end

  private
  def create_params
    params.require(:blog).permit(:title, :sentence)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blogs/index.html.haml
.main-contents
  .main-wrapper
    .header-image
    .header
      .header__leftbox
        .header__leftbox__title
          Labor and Social Security Atterney
          %br
          × Engineer
      .header__rightbox
        %ul#top-select
          %li.topselect= link_to 'BLOG', href="#blog"
          %li.topselect= link_to 'ABOUT ME', href="#aboutme"
          %li.topselect= link_to 'INSTAGRAM', 'https://www.instagram.com/makun_0910/'
    .center
      .center__blog
        .center__blog__title
          %h2#blog BLOG
        .center__blog__box
          %ul#main-title
            - @blogs.each do |blog|
              %li#center__blog__box-left
                = link_to "#{blog.title}", blog_path(blog.id), method: :get, class: "detail_blog"
            = paginate(@blogs)
          .center__blog__box-image
          = image_tag "https://pakutaso.cdn.rabify.me/shared/img/thumb/elly181027001.jpg?d=500", class: "blog-image"
          .center__blog__box-btn
          %input{onclick: "window.open('/blogs/new')", type: "button", value: "cookie", class: "create-btn"}/
      .center__aboutme
        .center__aboutme__title
          %h2#aboutme ABOUT ME
        .center__aboutme-box
          .center__aboutme-box__image
          = image_tag "CYMERA_20140407_114405.JPG", class: "profile-image"
          .center__aboutme-box__profile
            %h3 まーくん　福岡県出身　９月１０日生まれ
            %br
            %h3 大学卒業後、スタバでバイトをしながらバンド活動に打ち込む
            %br
            %h3 なんか資格を持っておいたほうがいいかなと思いとりあえず宅建を取得しておく
            %br
            %h3 ある日、労災疾病研究のお手伝いをやらないかと声をかけられ二つ返事で快諾
            %br
            %h3 研究終了後は社労士法人に勤め、社労士＆PSWを取得する
            %br
            %h3 自分の本当にやりたいことはなんだろうと人生を模索中、プログラミングに出会う
            %br
            %h3 社労士 × エンジニアとしての道を開拓奮闘中　← now!
      .center__contact
        .center__contact__title
          CONTACT
        .center__contact-box
          .center__contact-box__followme
            FOLLOW ME !!
            .center__contact-box__image
            = link_to image_tag(src="インスタグラムのシンプルなロゴのアイコン 1.jpeg", class: "instagram-icon"), "https://www.instagram.com/makun_0910/"
            = image_tag "https://cdn.pixabay.com/photo/2013/07/12/17/13/falling-151819_1280.png", class: "human-image"
          -# .center__contact-box__photos
          -#   .center__contact-box__photos-1
          -#     %blockquote.instagram-media{"data-instgrm-permalink" => "https://www.instagram.com/p/BsIOJuoBVFU/?utm_source=ig_embed&utm_campaign=loading", "data-instgrm-version" => "12", :style => " background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:200px; min-width:200px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"}
          -#     %script{:async => "", :src => "//www.instagram.com/embed.js"}
          -#   .center__contact-box__photos-2
          -#     %blockquote.instagram-media{"data-instgrm-permalink" => "https://www.instagram.com/p/Bnym5PkFP81/?utm_source=ig_embed&utm_campaign=loading", "data-instgrm-version" => "12", :style => " background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:200px; min-width:200px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"}
          -#     %script{:async => "", :src => "//www.instagram.com/embed.js"}
          -#   .center__contact-box__photos-3
          -#     %blockquote.instagram-media{"data-instgrm-permalink" => "https://www.instagram.com/p/Bm5p98hFiXq/?utm_source=ig_embed&utm_campaign=loading", "data-instgrm-version" => "12", :style => " background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:200px; min-width:200px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"}
          -#     %script{:async => "", :src => "//www.instagram.com/embed.js"}

    .footer
      .footer__message
        thanks!




-# %ul#gallery.gallery
-# %script{:src => "https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"}
-# %script{:src => "js/script.js"}

-# :javascript
-#   $(function(){
-#     $.ajax({
-#       type: 'GET',
-#       url: 'https://graph.facebook.com/v3.0/110054767088072?fields=name%2Cmedia.limit(4)%7Bcaption%2Clike_count%2Cmedia_url%2Cpermalink%2Ctimestamp%2Cusername%7D&access_token=EAAIIxe7sZC90BAPLYTygXJZBIVAQ0kbzoymx7xr0PA2uxkrlBlHj3k7LQdpaerWZBcSstbz1o3zV4qcs5oN6RyZBwsUke2BwdZCea9nxwYtxwNvyLQbJf1mXBssY4ja2CPhdOrgHpFwW7DVeCLW2Ksy8KWftZAK2zuZByVRXIP2j3VhMPZCF5PVZC',
-#       dataType: 'json',
-#       success: function(json) {
        
-#           var html = '';
-#           var insta = json.media.data;
-#           for (var i = 0; i < insta.length; i++) {
-#         html += '<div ><a href="' + insta[i].permalink + '" target="_blank"><img src="' + insta[i].media_url + '"></a></div>';
-#           }
-#             $("#instafeed").append(html);			
-#       },
-#       error: function() {
-#         error
-#       }
-#     });
-#   });

-# :javascript
-#   $(function(){
-#     $.getJSON("php/instagram.php", function(instagram_data){

-#     const gallery_data = instagram_data["business_discovery"]["media"]["data"];
-#     let photos = "";
-#     const photo_length = 9;

-#     for(let i = 0; i < photo_length ;i++){
-#     photos += '<li class="gallery-item"><img src="' + gallery_data[i].media_url + '"></li>';
-#     }
-#     $("#gallery").append(photos);

-#     });
-#   });

app/views/blogs/list.html.haml
.main-contents
  .main-wrapper
    .header-image
    .header
      .header__leftbox
        .header__leftbox__title
          Labor and Social Security Atterney
          %br
          × Engineer
      .header__rightbox
        %ul#top-select
          %li.topselect= link_to 'INDEX', blogs_path
          %li.topselect= link_to 'INSTAGRAM', 'https://www.instagram.com/makun_0910/'
    .list-contents
      .list-contents-wrapper
        = image_tag "https://cdn.pixabay.com/photo/2013/07/12/19/21/cabaret-154609__480.png", class: "list-image"
        .list-contents-wrapper__title
          - @blogs.each do |blog|
            %li#bloglist
              = blog[:created_at].strftime("%Y/%m/%d") 
              = link_to "　　#{blog.title}", blog_path(blog.id), method: :get, class: "detail_blog"
        = paginate(@blogs)
-#     .footer__list
-#       .footer__list__message
-#         thanks!

app/views/blogs/new.html.haml
= form_for(@blog, url: '/blogs' ) do |f|
  .blog__create
  = f.text_field :title, class: "title", placeholder: "title"
  = f.text_area :sentence, class: "text", placeholder: "text"    
  = f.text_area :bullet, class: "bullet", placeholder: "まとめ" 
  = f.submit '作成完了', class: "complete-btn"    

app/views/blogs/opening.html.haml
.contents
  .contents-black
    .fadein_first
      Labor and Social Security Attorney
    .fadein_second
      ×
    .fadein_last
      Enjineer

:javascript
%body{:onload => "setTimeout(\"location.href='/blogs'\",9000)"}

app/views/blogs/show.html.haml
.main-contents
  .main-wrapper
    .header-image
    .header
      .header__leftbox
        .header__leftbox__title
          Labor and Social Security Atterney
          %br
          × Engineer
      .header__rightbox
        %ul#top-select
          %li.topselect= link_to 'INDEX', blogs_path
          %li.topselect= link_to 'LIST', list_blogs_path
          %li.topselect= link_to 'INSTAGRAM', 'https://www.instagram.com/makun_0910/'

    .mainblog
      .mainblog-wrapper
        .mainblog-wrapper__title
          #{@blog.title}
        .mainblog-wrapper__main
          = safe_join(@blog.sentence.split("\n"), tag(:br))

    .maindigest
      .maindigest-wrapper
        %p1 SUMMARY
        .maindigest-wrapper__bullet
          = safe_join(@blog.bullet.split("\n"), tag(:br))
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "charset=UTF-8", "http-equiv" => "Content-Type"}/
    -# %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    -# %meta{:content => "ie=edge", "http-equiv" => "X-UA-Compatible"}/
    -# %link{:href => "css/style.css", :rel => "stylesheet"}/
    %title LSSA×ENJINEER
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield